### PR TITLE
Various fixes pulled from dempsey kernel

### PR DESCRIPTION
**Pull request by hampsterblade**
Kernel level ringtone fix.
Also a fix for some GPS and bluetooth stuff.
800Mhz wake lock when charging raised to 1000Mhz

### CODE REVIEW

**Comment by maxfierke** [comment]
Have these been tested?

**Comment by hampsterblade** [comment]
Gaming is faster on charger now.  Bluetooth is timing out, but I think I know how to fix it.  Working on testing the ringtones.  My phone gets bad signal in CM

**Comment by maxfierke** [comment]
I'm going to wait until tomorrow when I have some time to test these changes and do some more work on this before I merge this pull request.

**Comment by hampsterblade** [comment]
Ok, then. I'm investigating radio issues now, as they are the one thing that keeps CM unusable for me

**Comment by Fluidification** [comment]
what radio issue?

**Comment by hampsterblade** [comment]
It has major radio issues in my service area.  Had the same problem last time I was on CM7 and is why I flashed away.  Tends to not like to connect to a network unless I have perfect 4G signal.

**Comment by Fluidification** [comment]
Also, whenever in a dead zone, radio tends to die.

You need to restart or flight mode to restore the rild.

**Comment by maxfierke** [comment]
The aries kernel tree has a config option like CONFIG_MODEM_HAS_CRAPPY_BOOTLOADER. It may apply to ours too. Try using that and seeing if it improves modem reliability.

**Comment by hampsterblade** [comment]
I'll look into it.  The ringtone kernel fix didn't ring. I'll have to look into it more.

**Comment by maxfierke** [comment]
I'm closing this until I've decided what I want to do with it. This discussion is pointless.

**Pull request closed without merging**
