### PR TITLE
voodoo sound for CM7

### PR DESCRIPTION
**Pull request by Fluidification**
Title says it.

I didn't know how else to do it, so now it's a new request but with only 1 commit.

### CODE REVIEW

**Comment by maxfierke** [comment]
Thank you! I will merge this within the next couple of days. I need to tie up some loose ends first.

**Comment by Fluidification** [comment]
have fun!

**Comment by maxfierke** [comment]
You broke it again. Stop adding commits. They get automatically added to pull requests. Please just create a separate branch for voodoo sound and don't touch it, other than the voodoo sound commit. Make a pull request using that branch.

**Comment by Fluidification** [comment]
i'll fix it

**Pull request closed without merging**
