### PR TITLE
voodoo sound

### PR DESCRIPTION
**Pull request by Fluidification**
also, ignore the support 10 fingers commit. I don't know how to remove it.

see if you like.

### CODE REVIEW

**Comment by maxfierke** [comment]
We're getting to the point where we might be able to merge voodoo sound soon. Could you condense it all into one commit though, please?

Just copy the affected files out, clone a clean version of the teamacid tree, copy in your modified files, commit the changes, and then force push them to your branch. The merge request should update with your one commit at that point.

If you're unsure how to do something I told you, Googling "git force push" or whatever should turn up a good answer right away. Thanks!

**Comment by Fluidification** [comment]
will do soon.

**Comment by Fluidification** [comment]
to which branch..

If i delete my existing branch, clone a new copy, push the files, then what branch should I push to if there would be nothing left?  can I just close this request and open a new one?

**Comment by maxfierke** [comment]
The pull request will update itsself based on the contents of your
repository. Just apply the voodoo sound changes to a fresh teamacid clone
and "git push -f" to your github repo.
On Jun 5, 2012 9:17 PM, "Airfluip" <
reply@reply.github.com>
wrote:

**Pull request closed without merging**
