### PR TITLE
voodoo sound

### PR DESCRIPTION
**Pull request by Fluidification**
Here, from a different, clean branch.

### CODE REVIEW

**Comment by maxfierke** [comment]
Schweet.... I'll merge this once I finish up what I've got going on in my tree.

**Comment by Fluidification** [comment]
merging it for the upcoming build tonight?

**Comment by maxfierke** [comment]
Potentially.
On Jun 9, 2012 9:49 PM, "Airfluip" <
reply@reply.github.com>
wrote:

**Comment by bhundven** [comment]
This is what will get this merged.

Can you build this, and have you tested all of the voodoo sound features.
Does it all work and do you get popping or fizzing sounds?

Recording works? Playback works, as well as the other modes?

**Comment by Fluidification** [comment]
unfortunately, I haven't tested it. I've been away and have been working from a laptop and very slow internet.

**Comment by bhundven** [comment]
I'm not able to test this right now. If someone can test this change, and report back issues, please do :D

It would be most appreciated! If everything just works, lets merge this stuff!

**Comment by fbis251** [comment]
This pull request is broken and won't compile. Please test your pull requests before submitting them next time.

**Pull request closed without merging**
